### ISSUE TITLE
"enabled by information biomacromolecule (CHEBI:33695)" is automatically added (ref: gomodel:5dd88cab00000142)

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/noctua-models#133] opened 2019-11-26 23:48 UTC
When creating this model, "enabled by : gene" and "has_input : gene" was automatically updated to 
"information biomacromolecule (CHEBI:33695)gene"

This happened when creating annotation in the Noctua form, and when editing in the graph interface.

  (optional back ref: http://noctua.berkeleybop.org/editor/graph/gomodel:5dd88cab00000142)

**Comment by kltm** [comment] 2019-11-26 23:55
For the time being, this is a duplicate of https://github.com/geneontology/noctua/issues/638
We will be reverting the code that does this for the time being.

**Closed by kltm** 2019-11-26 23:55 UTC
